### Rotas normais
GET http://localhost:3333/

###

GET http://localhost:3333/marcas

###

GET http://localhost:3333/marcas/199



### 
POST http://localhost:3333/api/sync/marcas

###

POST http://localhost:3333/api/sync/produtos

###

POST http://localhost:3333/api/sync/pedidos

###


POST http://localhost:3333/api/sync/all